version: '3.8'

services:
  # BFF Service - Development with Hot Reload
  bff-dev:
    build:
      context: ./apps/backend/bff
      dockerfile: Containerfile.dev
    container_name: swipick-bff-dev
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - PORT=9000
      - GAMING_SERVICES_URL=http://gaming-services-dev:3000
    volumes:
      - ./apps/backend/bff/src:/app/src:ro
      - ./apps/backend/bff/package.json:/app/package.json:ro
      - ./apps/backend/bff/tsconfig.json:/app/tsconfig.json:ro
    depends_on:
      - gaming-services-dev
    networks:
      - swipick-dev-network
    restart: unless-stopped

  # Gaming Services - Development with Hot Reload
  gaming-services-dev:
    build:
      context: ./apps/backend/gaming-services
      dockerfile: Containerfile.dev
    container_name: swipick-gaming-services-dev
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WEBSOCKET_PORT=3001
      - API_FOOTBALL_URL=https://api-football-v1.p.rapidapi.com/v3
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY}
      - REDIS_URL=redis://redis-dev:6379
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres-dev:5432/swipick_gaming_dev
    volumes:
      - ./apps/backend/gaming-services/src:/app/src:ro
      - ./apps/backend/gaming-services/package.json:/app/package.json:ro
      - ./apps/backend/gaming-services/tsconfig.json:/app/tsconfig.json:ro
    depends_on:
      - postgres-dev
      - redis-dev
    networks:
      - swipick-dev-network
    restart: unless-stopped

  # PostgreSQL Database - Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: swipick-postgres-dev
    environment:
      - POSTGRES_DB=swipick_gaming_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    networks:
      - swipick-dev-network
    restart: unless-stopped

  # Redis Cache - Development
  redis-dev:
    image: redis:7-alpine
    container_name: swipick-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    networks:
      - swipick-dev-network
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  swipick-dev-network:
    driver: bridge
