[phases.setup]
nixPkgs = ['nodejs_20']

[variables]
FORCE_REBUILD = "2025-08-13-v2"

[phases.install]
cmds = [
  'npm ci'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'npm run start:prod'