[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install --omit=dev']

[phases.build]
cmds = [
  'npm run build --workspace=@swipick/common',
  'npm run build --workspace=@swipick/gaming-services'
]

[start]
cmd = 'npm run start:prod --workspace=@swipick/gaming-services'
