[variables]
NODE_ENV = "production"
NIXPACKS_NO_CACHE = "1"

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install --omit=dev']

[phases.build]
cmds = [
  'rm -rf apps/backend/bff/dist/tsconfig.tsbuildinfo || true',
  'npm run build --workspace=@swipick/common',
  'npm run build --workspace=bff'
]

[start]
cmd = 'npm run start:prod --workspace=bff'
