-- Serie A Fixtures 2025 - Matchdays 1-10
-- Generated INSERT statements for fixtures table

INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Genoa', 'Lecce', '2025-08-23 00:00:00', 'Stadio Luigi Ferraris', 1, 'X', 0, 0, 'FINISHED', 'serie_a_2025_1_Genoa_vs_Lecce', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Sassuolo', 'Napoli', '2025-08-23 00:00:00', 'Mapei Stadium', 1, '2', 0, 2, 'FINISHED', 'serie_a_2025_1_Sassuolo_vs_Napoli', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Roma', 'Bologna', '2025-08-23 00:00:00', 'Stadio Olimpico', 1, '1', 1, 0, 'FINISHED', 'serie_a_2025_1_Roma_vs_Bologna', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Milan', 'Cremonese', '2025-08-23 00:00:00', 'San Siro', 1, '2', 1, 2, 'FINISHED', 'serie_a_2025_1_Milan_vs_Cremonese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cagliari', 'Fiorentina', '2025-08-24 00:00:00', 'Unipol Domus', 1, 'X', 1, 1, 'FINISHED', 'serie_a_2025_1_Cagliari_vs_Fiorentina', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Como', 'Lazio', '2025-08-24 00:00:00', 'Stadio Giuseppe Sinigaglia', 1, '1', 2, 0, 'FINISHED', 'serie_a_2025_1_Como_vs_Lazio', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Juventus', 'Parma', '2025-08-24 00:00:00', 'Allianz Stadium', 1, '1', 2, 0, 'FINISHED', 'serie_a_2025_1_Juventus_vs_Parma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Atalanta', 'Pisa', '2025-08-24 00:00:00', 'Gewiss Stadium', 1, 'X', 1, 1, 'FINISHED', 'serie_a_2025_1_Atalanta_vs_Pisa', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Udinese', 'Verona', '2025-08-25 00:00:00', 'Stadio Friuli', 1, 'X', 1, 1, 'FINISHED', 'serie_a_2025_1_Udinese_vs_Verona', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Inter', 'Torino', '2025-08-25 00:00:00', 'San Siro', 1, '1', 5, 0, 'FINISHED', 'serie_a_2025_1_Inter_vs_Torino', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cremonese', 'Sassuolo', '2025-08-29 00:00:00', 'Stadio Giovanni Zini', 2, '1', 3, 2, 'FINISHED', 'serie_a_2025_2_Cremonese_vs_Sassuolo', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Lecce', 'Milan', '2025-08-29 00:00:00', 'Stadio Via del Mare', 2, '2', 0, 2, 'FINISHED', 'serie_a_2025_2_Lecce_vs_Milan', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Bologna', 'Como', '2025-08-30 00:00:00', 'Stadio Renato DallAra', 2, '1', 1, 0, 'FINISHED', 'serie_a_2025_2_Bologna_vs_Como', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Parma', 'Atalanta', '2025-08-30 00:00:00', 'Stadio Ennio Tardini', 2, 'X', 1, 1, 'FINISHED', 'serie_a_2025_2_Parma_vs_Atalanta', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Napoli', 'Cagliari', '2025-08-30 00:00:00', 'Stadio Diego Armando Maradona', 2, '1', 1, 0, 'FINISHED', 'serie_a_2025_2_Napoli_vs_Cagliari', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Pisa', 'Roma', '2025-08-30 00:00:00', 'Arena Garibaldi', 2, '2', 0, 1, 'FINISHED', 'serie_a_2025_2_Pisa_vs_Roma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Torino', 'Fiorentina', '2025-08-31 00:00:00', 'Stadio Olimpico Grande Torino', 2, 'X', 0, 0, 'FINISHED', 'serie_a_2025_2_Torino_vs_Fiorentina', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Genoa', 'Juventus', '2025-08-31 00:00:00', 'Stadio Luigi Ferraris', 2, '2', 0, 1, 'FINISHED', 'serie_a_2025_2_Genoa_vs_Juventus', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Inter', 'Udinese', '2025-08-31 00:00:00', 'San Siro', 2, '2', 1, 2, 'FINISHED', 'serie_a_2025_2_Inter_vs_Udinese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Lazio', 'Verona', '2025-08-31 00:00:00', 'Stadio Olimpico', 2, '1', 4, 0, 'FINISHED', 'serie_a_2025_2_Lazio_vs_Verona', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cagliari', 'Parma', '2025-09-13 15:00:00', 'Unipol Domus', 3, 'X', 0, 0, 'FINISHED', 'serie_a_2025_3_Cagliari_vs_Parma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cagliari', 'Parma', '2025-09-13 14:00:00', 'Unipol Domus', 3, '1', 2, 0, 'FINISHED', 'serie_a_2025_3_Cagliari_vs_Parma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Juventus', 'Inter', '2025-09-13 17:00:00', 'Allianz Stadium', 3, '1', 4, 3, 'FINISHED', 'serie_a_2025_3_Juventus_vs_Inter', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Fiorentina', 'Napoli', '2025-09-13 19:45:00', 'Stadio Artemio Franchi', 3, '2', 1, 3, 'FINISHED', 'serie_a_2025_3_Fiorentina_vs_Napoli', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Roma', 'Torino', '2025-09-14 11:30:00', 'Stadio Olimpico', 3, '2', 0, 1, 'FINISHED', 'serie_a_2025_3_Roma_vs_Torino', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Atalanta', 'Lecce', '2025-09-14 14:00:00', 'Gewiss Stadium', 3, '1', 4, 1, 'FINISHED', 'serie_a_2025_3_Atalanta_vs_Lecce', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Pisa', 'Udinese', '2025-09-14 14:00:00', 'Arena Garibaldi', 3, '2', 0, 1, 'FINISHED', 'serie_a_2025_3_Pisa_vs_Udinese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Sassuolo', 'Lazio', '2025-09-14 17:00:00', 'Mapei Stadium', 3, '1', 1, 0, 'FINISHED', 'serie_a_2025_3_Sassuolo_vs_Lazio', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Milan', 'Bologna', '2025-09-14 19:45:00', 'San Siro', 3, 'X', 1, 1, 'FINISHED', 'serie_a_2025_3_Milan_vs_Bologna', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Verona', 'Cremonese', '2025-09-15 17:30:00', 'Stadio Marcantonio Bentegodi', 3, 0, 'X', 0, 'FINISHED', 'serie_a_2025_3_Verona_vs_Cremonese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Como', 'Genoa', '2025-09-15 19:45:00', 'Stadio Giuseppe Sinigaglia', 3, 1, 'X', 1, 'FINISHED', 'serie_a_2025_3_Como_vs_Genoa', NOW(), NOW());
-- Serie A Matchday 4 Fixtures - Corrected based on image data
-- All times are in Italy time (CET/CEST)

-- Match played on September 19, 2025 (Yesterday)
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Lecce', 'Cagliari', '2025-09-19 19:45:00', 'Stadio Via del Mare', 4, '1', 1, 2, 'FINISHED', 'serie_a_2025_4_Lecce_vs_Cagliari', NOW(), NOW());

-- Matches for Today (September 20, 2025)
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Bologna', 'Genoa', '2025-09-20 15:00:00', 'Stadio Renato Dall Ara', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Bologna_vs_Genoa', NOW(), NOW());

INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Verona', 'Juventus', '2025-09-20 18:00:00', 'Stadio Marcantonio Bentegodi', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Verona_vs_Juventus', NOW(), NOW());

INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Udinese', 'Milan', '2025-09-20 20:45:00', 'Stadio Friuli', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Udinese_vs_Milan', NOW(), NOW());

-- Matches for Tomorrow (September 21, 2025)
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Lazio', 'Roma', '2025-09-21 12:30:00', 'Stadio Olimpico', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Lazio_vs_Roma', NOW(), NOW());

INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Torino', 'Atalanta', '2025-09-21 15:00:00', 'Stadio Olimpico Grande Torino', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Torino_vs_Atalanta', NOW(), NOW());

INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Cremonese', 'Parma', '2025-09-21 15:00:00', 'Stadio Giovanni Zini', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Cremonese_vs_Parma', NOW(), NOW());

INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Fiorentina', 'Como', '2025-09-21 18:00:00', 'Stadio Artemio Franchi', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Fiorentina_vs_Como', NOW(), NOW());

-- Match for Monday (September 22, 2025)
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Inter', 'Sassuolo', '2025-09-22 20:45:00', 'San Siro', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Inter_vs_Sassuolo', NOW(), NOW());

INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) 
VALUES ('Napoli', 'Pisa', '2025-09-22 20:45:00', 'Stadio Diego Armando Maradona', 4, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_4_Napoli_vs_Pisa', NOW(), NOW());


INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Atalanta', 'Cremonese', '2025-09-28 15:00:00', 'Gewiss Stadium', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Atalanta_vs_Cremonese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Como', 'Verona', '2025-09-28 15:00:00', 'Stadio Giuseppe Sinigaglia', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Como_vs_Verona', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Fiorentina', 'Lecce', '2025-09-28 15:00:00', 'Stadio Artemio Franchi', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Fiorentina_vs_Lecce', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Juventus', 'Bologna', '2025-09-28 18:00:00', 'Allianz Stadium', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Juventus_vs_Bologna', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Pisa', 'Lazio', '2025-09-29 12:30:00', 'Arena Garibaldi', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Pisa_vs_Lazio', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Roma', 'Udinese', '2025-09-29 15:00:00', 'Stadio Olimpico', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Roma_vs_Udinese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Sassuolo', 'Inter', '2025-09-29 15:00:00', 'Mapei Stadium', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Sassuolo_vs_Inter', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Torino', 'Napoli', '2025-09-29 18:00:00', 'Stadio Olimpico Grande Torino', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Torino_vs_Napoli', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cagliari', 'Milan', '2025-09-30 20:45:00', 'Unipol Domus', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Cagliari_vs_Milan', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Genoa', 'Parma', '2025-09-30 20:45:00', 'Stadio Luigi Ferraris', 5, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_5_Genoa_vs_Parma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Bologna', 'Atalanta', '2025-10-05 15:00:00', 'Stadio Renato Dall Ara', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Bologna_vs_Atalanta', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cremonese', 'Fiorentina', '2025-10-05 15:00:00', 'Stadio Giovanni Zini', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Cremonese_vs_Fiorentina', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Inter', 'Roma', '2025-10-05 18:00:00', 'San Siro', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Inter_vs_Roma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Lazio', 'Genoa', '2025-10-06 12:30:00', 'Stadio Olimpico', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Lazio_vs_Genoa', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Lecce', 'Sassuolo', '2025-10-06 15:00:00', 'Stadio Via del Mare', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Lecce_vs_Sassuolo', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Milan', 'Juventus', '2025-10-06 15:00:00', 'San Siro', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Milan_vs_Juventus', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Napoli', 'Como', '2025-10-06 15:00:00', 'Stadio Diego Armando Maradona', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Napoli_vs_Como', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Parma', 'Pisa', '2025-10-06 18:00:00', 'Stadio Ennio Tardini', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Parma_vs_Pisa', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Udinese', 'Cagliari', '2025-10-06 18:00:00', 'Stadio Friuli', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Udinese_vs_Cagliari', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Verona', 'Torino', '2025-10-06 20:45:00', 'Stadio Marc Antonio Bentegodi', 6, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_6_Verona_vs_Torino', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Atalanta', 'Genoa', '2025-10-19 15:00:00', 'Gewiss Stadium', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Atalanta_vs_Genoa', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cagliari', 'Bologna', '2025-10-19 15:00:00', 'Unipol Domus', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Cagliari_vs_Bologna', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Como', 'Parma', '2025-10-19 15:00:00', 'Stadio Giuseppe Sinigaglia', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Como_vs_Parma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Fiorentina', 'Milan', '2025-10-19 18:00:00', 'Stadio Artemio Franchi', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Fiorentina_vs_Milan', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Juventus', 'Lazio', '2025-10-20 12:30:00', 'Allianz Stadium', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Juventus_vs_Lazio', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Pisa', 'Napoli', '2025-10-20 15:00:00', 'Arena Garibaldi', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Pisa_vs_Napoli', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Roma', 'Inter', '2025-10-20 20:45:00', 'Stadio Olimpico', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Roma_vs_Inter', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Sassuolo', 'Udinese', '2025-10-20 20:45:00', 'Mapei Stadium', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Sassuolo_vs_Udinese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Torino', 'Lecce', '2025-10-21 20:45:00', 'Stadio Olimpico Grande Torino', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Torino_vs_Lecce', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Verona', 'Cremonese', '2025-10-21 20:45:00', 'Stadio Marc Antonio Bentegodi', 7, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_7_Verona_vs_Cremonese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Bologna', 'Milan', '2025-10-26 15:00:00', 'Stadio Renato Dall Ara', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Bologna_vs_Milan', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cremonese', 'Udinese', '2025-10-26 15:00:00', 'Stadio Giovanni Zini', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Cremonese_vs_Udinese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Genoa', 'Fiorentina', '2025-10-26 15:00:00', 'Stadio Luigi Ferraris', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Genoa_vs_Fiorentina', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Inter', 'Juventus', '2025-10-26 18:00:00', 'San Siro', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Inter_vs_Juventus', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Lazio', 'Torino', '2025-10-27 12:30:00', 'Stadio Olimpico', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Lazio_vs_Torino', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Lecce', 'Napoli', '2025-10-27 15:00:00', 'Stadio Via del Mare', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Lecce_vs_Napoli', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Parma', 'Roma', '2025-10-27 15:00:00', 'Stadio Ennio Tardini', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Parma_vs_Roma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Pisa', 'Atalanta', '2025-10-27 18:00:00', 'Arena Garibaldi', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Pisa_vs_Atalanta', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Udinese', 'Como', '2025-10-27 20:45:00', 'Stadio Friuli', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Udinese_vs_Como', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Verona', 'Sassuolo', '2025-10-27 20:45:00', 'Stadio Marc Antonio Bentegodi', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Verona_vs_Sassuolo', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cagliari', 'Lazio', '2025-10-28 20:45:00', 'Unipol Domus', 8, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_8_Cagliari_vs_Lazio', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Atalanta', 'Verona', '2025-11-02 15:00:00', 'Gewiss Stadium', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Atalanta_vs_Verona', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Como', 'Bologna', '2025-11-02 15:00:00', 'Stadio Giuseppe Sinigaglia', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Como_vs_Bologna', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Fiorentina', 'Roma', '2025-11-02 15:00:00', 'Stadio Artemio Franchi', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Fiorentina_vs_Roma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Juventus', 'Torino', '2025-11-02 18:00:00', 'Allianz Stadium', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Juventus_vs_Torino', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Milan', 'Napoli', '2025-11-03 12:30:00', 'San Siro', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Milan_vs_Napoli', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Sassuolo', 'Cagliari', '2025-11-03 15:00:00', 'Mapei Stadium', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Sassuolo_vs_Cagliari', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Udinese', 'Lecce', '2025-11-03 15:00:00', 'Stadio Friuli', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Udinese_vs_Lecce', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Roma', 'Lazio', '2025-11-03 18:00:00', 'Stadio Olimpico', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Roma_vs_Lazio', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cremonese', 'Inter', '2025-11-03 20:45:00', 'Stadio Giovanni Zini', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Cremonese_vs_Inter', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Parma', 'Genoa', '2025-11-04 20:45:00', 'Stadio Ennio Tardini', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Parma_vs_Genoa', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Pisa', 'Como', '2025-11-04 20:45:00', 'Arena Garibaldi', 9, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_9_Pisa_vs_Como', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Bologna', 'Lecce', '2025-11-09 15:00:00', 'Stadio Renato Dall Ara', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Bologna_vs_Lecce', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cagliari', 'Atalanta', '2025-11-09 15:00:00', 'Unipol Domus', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Cagliari_vs_Atalanta', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Como', 'Fiorentina', '2025-11-09 15:00:00', 'Stadio Giuseppe Sinigaglia', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Como_vs_Fiorentina', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Genoa', 'Udinese', '2025-11-09 18:00:00', 'Stadio Luigi Ferraris', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Genoa_vs_Udinese', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Inter', 'Parma', '2025-11-10 12:30:00', 'San Siro', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Inter_vs_Parma', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Lazio', 'Milan', '2025-11-10 15:00:00', 'Stadio Olimpico', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Lazio_vs_Milan', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Napoli', 'Verona', '2025-11-10 15:00:00', 'Stadio Diego Armando Maradona', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Napoli_vs_Verona', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Roma', 'Sassuolo', '2025-11-10 15:00:00', 'Stadio Olimpico', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Roma_vs_Sassuolo', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Torino', 'Pisa', '2025-11-10 18:00:00', 'Stadio Olimpico Grande Torino', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Torino_vs_Pisa', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Lecce', 'Juventus', '2025-11-10 20:45:00', 'Stadio Via del Mare', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Lecce_vs_Juventus', NOW(), NOW());
INSERT INTO fixtures (home_team, away_team, match_date, stadium, week, result, home_score, away_score, status, external_api_id, created_at, updated_at) VALUES ('Cremonese', 'Cagliari', '2025-11-11 20:45:00', 'Stadio Giovanni Zini', 10, 'X', 0, 0, 'SCHEDULED', 'serie_a_2025_10_Cremonese_vs_Cagliari', NOW(), NOW());