[phases.setup]
nixPkgs = ['nodejs_20']

[variables]
FORCE_REBUILD = "2025-08-13-v3-BFF-FIX"

[phases.install]
cmds = [
  'cd ../../../ && npm ci'
]

[phases.build]
cmds = [
  'cd ../../../ && npm run build --workspace=apps/backend/bff'
]

[start]
cmd = 'cd ../../../ && npm run start:prod --workspace=apps/backend/bff'
