[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'cd /app && npm ci && cd /app/apps/backend/bff'
]

[phases.build]
cmds = [
  'cd /app && npm run build --workspace=bff && cd /app/apps/backend/bff'
]

[start]
cmd = 'npm run start:prod'
